name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Java e Android SDK
      uses: android-actions/setup-android@v2

    - name: Instalar dependências do projeto
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        pip install buildozer cython

    - name: Build APK
      run: |
        cd caminho/do/seu/app/
        buildozer android debug

    - name: Enviar APK como artefato
      uses: actions/upload-artifact@v4
      with:
        name: carteira-apk
        path: caminho/do/seu/app/bin/*.apk
        
